language: c
compiler: gcc
os: linux

## turn off email notifications
# notifications:
#   email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -q libfftw3-dev

# install:

script: ./bootstrap.sh && ./configure --enable-all --enable-openmp && make && make check

## print config.log for debugging
after_failure: "cat config.log"

