language: c
compiler:
    - gcc
    - clang
os: linux

# Turn off sudo to run on container based infrastructure.
sudo: false

addons:
  apt:
    packages:
    - libfftw3-dev
    - libcunit1-dev

env:
  - WINDOW=kaiserbessel
  - WINDOW=gaussian
  - WINDOW=bspline
  - WINDOW=sinc

# Compile, link, and run tests.
script: ./bootstrap.sh && ./configure --with-window=$WINDOW --enable-all && make && make check

## Print config.log for debugging.
after_failure: "cat config.log"

# Turn off email notifications.
notifications:
   email: false
